// 系统架构图 - Part 3: 入库 Pipeline + 权限 + 部署
const { H1, H2, H3, P, BR, BULLET, NUM, makeTable, callout, code } = require('./common');

module.exports.part3 = () => [
  H1("4. 入库 Pipeline 详图"),

  H2("4.1 文档入库总流程"),
  code([
    "[上传] → [命名校验] → [Omni 元数据抽取]",
    "                            ↓",
    "                  [客户别名匹配 + 业务方审核]",
    "                            ↓",
    "                  [结构化路径判定]",
    "                  ┌─────────┴─────────┐",
    "                  ↓                   ↓",
    "         结构化表（Excel）       非结构化（Word/PPT/PDF）",
    "                  ↓                   ↓",
    "         导入 PostgreSQL    [文档解析 + 切片]",
    "         业务表             ┌─────────┴────────┐",
    "                            ↓                  ↓",
    "                       纯文本块          图片/PPT 页",
    "                            ↓                  ↓",
    "                            │       Omni 描述（VLM）",
    "                            ↓                  ↓",
    "                       bge-m3 向量化（合并）",
    "                            ↓",
    "                       Qdrant 入库（带 metadata）",
  ].join("\n")),

  H2("4.2 结构化双轨示例"),
  makeTable(
    ["输入文件", "类型判定", "处理路径", "落地表/库"],
    [
      ["客户清单.xlsx", "结构化", "解析为 DataFrame → 入 PG", "customer 表"],
      ["维保记录.xlsx", "结构化", "按行入 PG", "maintenance_records 表"],
      ["产品手册.docx", "非结构化", "切片 → 向量化", "Qdrant"],
      ["调研报告.pdf", "非结构化", "切片 + 图片 Omni 描述", "Qdrant"],
      ["方案演示.pptx", "视觉文档", "每页转图 + Omni 描述", "Qdrant"],
      ["财务报表.xlsx", "复杂表格", "截图 + Omni 描述", "Qdrant"],
    ],
    [2200, 1500, 3300, 2360]
  ),

  H2("4.3 PPT 入库详细流程"),
  code([
    "ABC公司产品演示_20240615.pptx (50 页)",
    "  ↓",
    "[1] python-pptx 解析",
    "    ├─ 提取每页标题、文字框文本、演讲者备注",
    "    └─ 每页转 PNG（1024px 宽）",
    "  ↓",
    "[2] 对每页 PNG 调用 Omni:",
    "    Prompt: 「描述这张幻灯片：标题、要点、图表、关键数据」",
    "    输出: 结构化描述",
    "  ↓",
    "[3] 拼接文本表示:",
    "    = 标题 + Omni描述 + 文字框文本 + 演讲者备注",
    "  ↓",
    "[4] bge-m3 向量化（每页 1 个 chunk）",
    "  ↓",
    "[5] 入 Qdrant，metadata = {",
    "      customer_id: CUST_001,",
    "      doc_type: 'presentation',",
    "      event_date: '2024-06-15',",
    "      page_num: 1-50,",
    "      doc_id: ...,",
    "    }",
  ].join("\n")),
  BR(),

  H1("5. 权限模型"),

  H2("5.1 三层权限"),
  code([
    "┌─────────────────────────────────────┐",
    "│  Layer 1: 用户认证 (Authentication) │",
    "│  - 公司 SSO / 邮箱密码                │",
    "└──────────────┬──────────────────────┘",
    "               ↓",
    "┌─────────────────────────────────────┐",
    "│  Layer 2: 客户级 ACL                 │",
    "│  user_customer_acl 表:               │",
    "│    sales_001 → [CUST_A, CUST_B]      │",
    "│    service_001 → [CUST_A, CUST_C]    │",
    "│    manager → ALL                     │",
    "└──────────────┬──────────────────────┘",
    "               ↓",
    "┌─────────────────────────────────────┐",
    "│  Layer 3: 文档类型 ACL               │",
    "│  document_type_acl 表:               │",
    "│    contract / quotation → 仅高管+财务 │",
    "│    delivery_* → 客户负责人+售后        │",
    "│    product_doc → 全员                 │",
    "└─────────────────────────────────────┘",
  ].join("\n")),

  H2("5.2 检索时的权限过滤"),
  code([
    "用户 sales_001 发起检索:",
    "  ↓",
    "查 user_customer_acl: allowed_customers = [CUST_A, CUST_B]",
    "查 user_role: role = 'sales'",
    "查 document_type_acl: allowed_doc_types = [delivery_*, product_doc, faq]",
    "  ↓",
    "Qdrant 检索条件:",
    "  filter: (",
    "    customer_id IN [CUST_A, CUST_B]",
    "    AND doc_type IN [allowed_doc_types]",
    "  )",
    "  ↓",
    "向量检索 + Rerank → 仅返回有权限的文档",
  ].join("\n")),
  BR(),

  H1("6. 部署架构"),

  H2("6.1 Docker Compose 服务清单"),
  makeTable(
    ["服务", "镜像", "端口", "数据卷"],
    [
      ["fastapi-backend", "自构建（Python 3.14）", "8000", "./logs"],
      ["nextjs-frontend", "自构建（基于 node:22-alpine）", "3000", "-"],
      ["qdrant", "qdrant/qdrant:latest", "6333", "./qdrant_data"],
      ["postgres", "postgres:16", "5432", "./pg_data"],
      ["redis", "redis:7", "6379", "-"],
      ["celery-worker", "复用 backend 镜像", "-", "./logs"],
      ["minio", "minio/minio:latest", "9000/9001", "./minio_data"],
      ["bge-m3", "infiniflow/bge-m3 或自定义", "8080", "./model_cache"],
    ],
    [2200, 3000, 1500, 2660]
  ),

  H2("6.2 环境变量（迁移友好关键）"),
  code([
    "# .env.example",
    "",
    "# === LLM/VLM ===",
    "LLM_PROVIDER=bailian            # 可选: bailian | ollama | openai",
    "LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1",
    "LLM_MODEL=qwen3.5-omni-flash",
    "LLM_API_KEY=sk-xxx",
    "",
    "# === Rerank ===",
    "RERANK_BASE_URL=https://dashscope.aliyuncs.com/api/v1/...",
    "RERANK_MODEL=gte-rerank-v2",
    "",
    "# === Embedding (本地) ===",
    "EMBED_BASE_URL=http://bge-m3:8080",
    "EMBED_MODEL=bge-m3",
    "",
    "# === 数据库 ===",
    "POSTGRES_URL=postgresql://user:pass@postgres:5432/rag",
    "QDRANT_URL=http://qdrant:6333",
    "REDIS_URL=redis://redis:6379",
    "MINIO_ENDPOINT=minio:9000",
    "",
    "# === 业务参数（迁移时可调） ===",
    "CHUNK_SIZE=800",
    "TOP_K=30",
    "RERANK_N=5",
    "TEMPERATURE=0.3",
  ].join("\n")),

  H2("6.3 迁移到全本地（未来）只需改 3 行"),
  code([
    "# 切换前（混合云）:",
    "LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1",
    "LLM_MODEL=qwen3.5-omni-flash",
    "RERANK_BASE_URL=https://dashscope.aliyuncs.com/...",
    "",
    "# 切换后（全本地）:",
    "LLM_BASE_URL=http://ollama:11434/v1     # ← 改这里",
    "LLM_MODEL=qwen2.5-vl:7b                  # ← 改这里",
    "RERANK_BASE_URL=http://bge-reranker:8080 # ← 改这里",
    "",
    "# 业务代码、Agent、Pipeline、前端 —— 完全不动",
  ].join("\n")),
  BR(),

  H1("7. 关键技术栈版本"),
  makeTable(
    ["组件", "版本"],
    [
      ["Python", "3.14"],
      ["FastAPI", "0.110+"],
      ["LlamaIndex", "0.10+"],
      ["Node.js", "22 LTS"],
      ["Next.js", "15"],
      ["Qdrant", "1.10+"],
      ["PostgreSQL", "16"],
      ["Redis", "7"],
      ["Celery", "5.3+"],
      ["bge-m3", "latest"],
      ["Docker", "24+"],
    ],
    [4000, 5360]
  ),

  new (require('docx').Paragraph)({ children: [new (require('docx').TextRun)({ text: "— 架构图文档结束 —", color: "808080" })], alignment: 1, spacing: { before: 400 } }),
];
