// 系统架构图 - Part 2: Agent 编排 + 查询 Pipeline
const { H1, H2, H3, P, BR, BULLET, NUM, makeTable, callout, code } = require('./common');

module.exports.part2 = () => [
  H1("2. Agent 编排架构"),

  H2("2.1 Router + 多 Agent 模式"),
  code([
    "                  ┌──────────────────┐",
    "                  │   用户输入        │",
    "                  │ (文本 + 可选图片) │",
    "                  └────────┬─────────┘",
    "                           ↓",
    "                  ┌──────────────────┐",
    "                  │ Router Agent     │",
    "                  │ - 意图识别        │",
    "                  │ - 会话上下文管理   │",
    "                  │ - 路由分发        │",
    "                  └────────┬─────────┘",
    "                           ↓",
    "         ┌─────────┬───────┴────────┬──────────┐",
    "         ↓         ↓                ↓          ↓",
    "    ┌─────────┐ ┌──────────┐ ┌────────────┐ ┌───────┐",
    "    │ BaseQA  │ │Comparison│ │ServicePath │ │FreeQA │",
    "    │ Agent   │ │ Agent    │ │ Agent      │ │ Agent │",
    "    │ (纯RAG) │ │(工作流1) │ │(工作流1)   │ │(工具2)│",
    "    └────┬────┘ └────┬─────┘ └─────┬──────┘ └───┬───┘",
    "         └───────────┴─────────────┴────────────┘",
    "                           ↓",
    "                  ┌──────────────────┐",
    "                  │  共享工具层       │",
    "                  │ - call_omni()    │",
    "                  │ - search_qdrant()│",
    "                  │ - query_pg()     │",
    "                  │ - rerank()       │",
    "                  └──────────────────┘",
  ].join("\n")),

  H2("2.2 Agent 形态对照"),
  makeTable(
    ["Agent", "形态", "适用场景", "Omni 调用次数"],
    [
      ["BaseQA Agent", "纯 Pipeline", "「这个产品支持什么协议？」", "1（生成答案）"],
      ["Comparison Agent", "工作流（形态1）", "「客户 A 和 B 的产品使用对比」", "3-4（识别→抽取→对比）"],
      ["ServicePath Agent", "工作流（形态1）", "「客户 ABC 的服务历程」", "N+1（每份文档抽事件 + 整合）"],
      ["FreeQA Agent", "工具调用（形态2）", "「我的客户里谁快续费了？」", "2-5（自主选工具）"],
    ],
    [2200, 1800, 3500, 1860]
  ),
  BR(),

  H1("3. 查询 Pipeline 详图"),

  H2("3.1 BaseQA Agent Pipeline（基础问答）"),
  code([
    "用户: 「我们的退款政策是几天？」",
    "  ↓",
    "Router: 识别为 base_qa → 转 BaseQA Agent",
    "  ↓",
    "BaseQA Agent:",
    "  1. （如带图）Omni 描述图片",
    "  2. bge-m3 向量化 query",
    "  3. Qdrant 检索 Top-30",
    "     filter: customer_id IN (user.allowed_customers)",
    "  4. gte-rerank-v2 精排 → Top-5",
    "  5. Omni 生成答案（含原文引用）",
    "  ↓",
    "返回: 「根据《退款政策v2.docx》第3节：7天无理由退款...」",
    "       [引用1: 退款政策v2.docx P3]",
  ].join("\n")),

  H2("3.2 Comparison Agent Pipeline（客户对比）"),
  code([
    "用户: 「客户A 和 客户B 的产品使用对比」",
    "  ↓",
    "Router: 识别为 customer_comparison → 转 Comparison Agent",
    "  ↓",
    "Step 1 - 实体识别（Omni 调用 #1）:",
    "  抽取: [客户A, 客户B] → 查 customer 表 → [CUST_A, CUST_B]",
    "  ↓",
    "Step 2 - 精确字段查询（不调 LLM）:",
    "  SELECT * FROM customer WHERE id IN (...)",
    "  SELECT * FROM customer_product WHERE customer_id IN (...)",
    "  SELECT * FROM contract WHERE customer_id IN (...)",
    "  → 拿到精确的产品/金额/续费数据",
    "  ↓",
    "Step 3 - 模糊字段检索:",
    "  Qdrant filter: customer_id = CUST_A → 检索使用情况文档",
    "  Qdrant filter: customer_id = CUST_B → 同上",
    "  ↓",
    "Step 4 - 多维度抽取（Omni 调用 #2、#3）:",
    "  对每个客户的文档，让 Omni 抽取「主要问题」「满意度」等",
    "  ↓",
    "Step 5 - 对比报告生成（Omni 调用 #4）:",
    "  输入: 精确字段 + 抽取的模糊字段",
    "  输出: 对比表 JSON + 销售话术建议",
    "  ↓",
    "返回: 前端渲染对比表组件 + 话术 Tips",
  ].join("\n")),

  H2("3.3 ServicePath Agent Pipeline（服务路径图）"),
  code([
    "用户: 「客户 ABC 的服务历程」",
    "  ↓",
    "Router: 识别为 service_path → 转 ServicePath Agent",
    "  ↓",
    "Step 1 - 客户识别（Omni 调用 #1）:",
    "  抽取: ABC → CUST_001",
    "  ↓",
    "Step 2 - 全档案检索（不走相似度，按 metadata 过滤）:",
    "  Qdrant: filter customer_id = CUST_001, sort by event_date ASC",
    "  PG: SELECT * FROM maintenance_records WHERE customer_id = ?",
    "  PG: SELECT * FROM contract WHERE customer_id = ?",
    "  → 拿到该客户全部相关文档与结构化记录",
    "  ↓",
    "Step 3 - 事件抽取（每份文档 1 次 Omni 调用）:",
    "  并发调用，每份输出: {date, event_type, summary, doc_ref}",
    "  ↓",
    "Step 4 - 时间轴整合（Omni 调用 #N+1）:",
    "  按 event_date 排序，去重合并",
    "  标记重大节点（故障/升级/续约）",
    "  生成「关键提示」（如「上次反馈培训不足，可主动补训」）",
    "  ↓",
    "返回: 前端时间轴组件 + 关键提示",
  ].join("\n")),
  BR(),
];
